### ISSUE TITLE
Crab Parachain Chain ---> Crab Parachain

### ISSUE THREAD

**Issue by 1022ranji** [darwinia-network/fee-market#18]
<img width="565" alt="image" src="https://user-images.githubusercontent.com/80877629/194842278-bdd45c3b-5ac6-4e65-beb0-aaf2215305e0.png">

**Comment by JayJay1024** [comment]
This market has been added, the data need to wait for the subgraph index

**Comment by ZolaxZola** [comment]
Misunderstood. Chain Name Error, we should remove the `Chain` of "Crab Parachain Chain"
