### ISSUE TITLE
After Modifying Collateral balance, The reduced balance should be returned to the relayer‘s personal account.

### ISSUE THREAD

**Issue by ZolaxZola** [darwinia-network/fee-market#41]
The reduced Tokens should be returned to the Relayer‘s personal account, but it is not. 
https://crab.subscan.io/extrinsic/12657131-1

**Comment by JayJay1024** [comment]
@AsceticBear  Is `updateLockedCollateral ` only supporting lock more? Is there a function that can lock less

<img width="1630" alt="image" src="https://user-images.githubusercontent.com/21007682/195782118-c6a1f6e5-534c-473d-b140-a220734f092e.png">

**Comment by AsceticBear** [comment]
@JayJay1024 @ZolaxZola I am planning to split the `updateLockedCollateral` into two calls in the next week. It would be easier to use that way.

**Comment by AsceticBear** [comment]
This is a runtime issue. I'll fix it before the next runtime upgrade.
