### ISSUE TITLE
After Canceling Relayer, the Collateral Balance should be returned to the relayer‘s personal account

### ISSUE THREAD

**Issue by ZolaxZola** [darwinia-network/fee-market#42]
After Canceling Relayer, the Collateral Balance should be returned to the relayer‘s personal account. But it is not.
https://crab.subscan.io/extrinsic/12657177-1

**Comment by JayJay1024** [comment]
cc @AsceticBear

**Comment by AsceticBear** [comment]
This is a runtime issue, I'll fix it before the next runtime release.

**Comment by ZolaxZola** [comment]
It could just be the data delay.  I will double-try later.

**Comment by ZolaxZola** [comment]
`5H9Aq1mZQh5yZBuNWqbSaZAmdiQFBWSdtzosSL3H6FNknLbW`
I tried canceling the relayer of this account. (collateral balance is 50 PRING)
Before canceling,  my available balance: 120 PRING
After canceling, my available balance: 137 PRING ( It should be 170 PRING)
https://pangolin.subscan.io/extrinsic/578453-1

**Comment by ZolaxZola** [comment]
<img width="1303" alt="image" src="https://user-images.githubusercontent.com/102211220/197669158-f5aedc62-75e4-4ca5-b756-381b29bfa263.png">
Staking_amount and FeeMarket_collateral are sharing the Locked Field.   
(Reference: https://wiki.polkadot.network/docs/learn-accounts#account-balance-types)
This issue can be ignored for now until the underlying design is modified.
