### ISSUE TITLE
Register Relayer Successfully, the Status, Collateral balance and Quote never updates

### ISSUE THREAD

**Issue by ZolaxZola** [darwinia-network/fee-market#54]
https://crab.subscan.io/tx/0x2e2dab2f0eb72f37411f27ebe9dacb5cc9a2bc257e1fc295e589cc31465853be
<img width="1255" alt="image" src="https://user-images.githubusercontent.com/102211220/196392912-7905b6eb-076a-4c32-a717-3949c90dda8d.png">
Unable to register relayer for now?

**Comment by JayJay1024** [comment]
Nope it can register for now. But it may be that the rpc on Crab is not stable. My registration on Pangolin is very smooth

**Comment by ZolaxZola** [comment]
55 minutes passed, the status is still unregistered. Is there some other issue rather than RPC?

**Comment by ZolaxZola** [comment]
https://crab.subscan.io/tx/0xffc6b90ecb8e14b1ce911d4182fcd4c0c185fcfc376b5c3c01bd843e2ffe9925
Crab Chain > Crab Parachian is the same issue.
