### ISSUE TITLE
When clicking “Orders” on the sidebar, the filter info should be cleared.

### ISSUE THREAD

**Issue by ZolaxZola** [darwinia-network/fee-market#68]
![image](https://user-images.githubusercontent.com/102211220/197507374-24c73a4f-bfaa-44ae-aef2-6c95c01bd199.png)

**Comment by JayJay1024** [comment]
It's weird why such behavior is needed

**Comment by JayJay1024** [comment]
I think it's not reasonable to click on the sidebar 「Orders」to clear the filter info

**Comment by ZolaxZola** [comment]
A click on the tab is considered as a refresh of the page and the previous search query, filters, and sorts would be updated. (which was what I described as "cleared filter info")  
Try searching on the issues page and clicking on the current tab. The search query, filters, and sorts will be cleared.
Currently, when we click the current "Orders" tab, the filter results will be updated but the filter criteria remain, which is inconsistent.
