### ISSUE TITLE
Date Selector Info Clearing is needed.

### ISSUE THREAD

**Issue by ZolaxZola** [darwinia-network/fee-market#69]
We should provide a Clear button for Date Selector Info.
Need some discussion here:Have we used customized components or not here? Should we combine the Start_Date and End_Date section into One Section? (Since components ux are not consistent with the indicator section.) 
![image](https://user-images.githubusercontent.com/102211220/197508747-2f1cba8f-66e5-4c02-a3df-e12a693eb98f.png)

**Comment by JayJay1024** [comment]
cc @isunaslabs

**Comment by isunaslabs** [comment]
@ZolaxZola Please check this functionality on https://feemarket-jkh29mafn-itering.vercel.app/orders . It's fixed. I'll tag you on Slack as well
