### ISSUE TITLE
order detail page error

### ISSUE THREAD

**Issue by ZolaxZola** [darwinia-network/fee-market#79]
<img width="1455" alt="image" src="https://user-images.githubusercontent.com/102211220/198193662-9639fd20-b54e-4adb-a3b8-d16b0c754c88.png">
<img width="1041" alt="image" src="https://user-images.githubusercontent.com/102211220/198193708-46329eee-202c-4826-a9b0-f232109511f5.png">

**Comment by JayJay1024** [comment]
Does the console have any error log

**Comment by ZolaxZola** [comment]
![image](https://user-images.githubusercontent.com/102211220/198207008-75ffd8a5-8ed3-43dc-86be-e8e30c0fce07.png)
