### ISSUE TITLE
Wrong Reward Data of the order

### ISSUE THREAD

**Issue by ZolaxZola** [darwinia-network/fee-market#86]
https://feemarket-stg.vercel.app/orders/details?from=darwinia-smart-chain&to=ethereum&lane=eth&nonce=0x1000000010000000000000006

https://darwinia.subscan.io/tx/0xc22f7b0ec26c3ff73deb5bbeb2c47f98d6c9e40e18fe53cf932e054e5fac02e8

Reward data should be

> duty_reward:     0
> delivery_reward: 4995
> confirm_reward:  5
> treasury_reward: 0

**Comment by JayJay1024** [comment]
> duty_reward: 0
> delivery_reward: 4995
> confirm_reward: 5
> treasury_reward: 0

Why is the reward this number

**Comment by ZolaxZola** [comment]
> > duty_reward: 0
> > delivery_reward: 4995
> > confirm_reward: 5
> > treasury_reward: 0
> 
> Why is the reward this number
@hujw77  please help confirm.

**Comment by JayJay1024** [comment]
I have fixed this issue, deploy a new version indexer, and is syncing block now
