### ISSUE TITLE
Pangoro >Pangolin after registered, the Collateral Balance and quote didn't update.

### ISSUE THREAD

**Issue by ZolaxZola** [darwinia-network/fee-market#88]
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/102211220/199219432-0259bae3-d114-46d8-bb7c-e602f3221686.png">
Pangoro >Pangolin after getting registered, the Collateral Balance and quotes didn't update.

**Comment by JayJay1024** [comment]
It looks fine
<img width="1447" alt="image" src="https://user-images.githubusercontent.com/21007682/199264946-5eae1368-6244-45a2-8998-a4c5c984ea9f.png">
<img width="771" alt="image" src="https://user-images.githubusercontent.com/21007682/199265030-b4a1626d-0860-4ddd-86f2-6dac2e88634a.png">

I tried it, and it will automatically update the data after registering
