### ISSUE TITLE
Pangoro > Pangolin: After reducing collateral balance, the transferrable balance didn't increase

### ISSUE THREAD

**Issue by ZolaxZola** [darwinia-network/fee-market#89]
[2tFLdCmtBi6XonCEn4UsWvna84yBs7L9NRWifvc3yj742asy
](https://pangoro.subscan.io/account/2tFLdCmtBi6XonCEn4UsWvna84yBs7L9NRWifvc3yj742asy)
After reducing the collateral balance, the transferrable balance didn't increase

Not sure if it's the same issue with https://github.com/darwinia-network/fee-market/issues/41

**Comment by JayJay1024** [comment]
I think because you have 80 ORING in others. Maybe you should `collateral` grater than 80 ORNG when you register, and check again.

<img width="1372" alt="image" src="https://user-images.githubusercontent.com/21007682/199269194-959eda60-832b-4cca-84e5-21cae51f5ef6.png">

**Comment by ZolaxZola** [comment]
The “Others” here is just the fee market collateral.  When depositing more into the collateral balance, the transferable balance reduces correctly. When withdrawing from the collateral balance, the transferable balance didn't change. 
Yalin has tried and found this, and I meet the same issue. 
(in my case, i update collateral from 80 to 40)

**Comment by JayJay1024** [comment]
But in my case, the `Others` doesn't mean fee market collateral. I register relayer with 300 ORING collateral, but `Others` is still 0

**Comment by AsceticBear** [comment]
This is the same issue with #41. Will be fixed in the next pangoro/pangolin release.
