### ISSUE TITLE
Second page content not included in search and sort range

### ISSUE THREAD

**Issue by ZolaxZola** [darwinia-network/fee-market#97]
**Describe the bug**
I cannot search for the relayer on the second page

**To Reproduce**
go to: https://feemarket.darwinia.network/relayers-overview?from=crab&to=darwinia
Search for `5DbwpVeELhVuPQPdKf7tRR1JDWEp6jGC6jRJqcy4hAnXy15b`
It shows no data  but there should be

**Screenshots**
<img width="1263" alt="image" src="https://user-images.githubusercontent.com/102211220/200719670-db6f3fa5-d76b-4488-8aa5-da3e4acea115.png">

**Additional context**
the sort function is similar: When sorting in descending order, the data on the second page does not participate in sorting
 <img width="1181" alt="image" src="https://user-images.githubusercontent.com/102211220/200720776-625f0003-e4b0-43d1-aec6-d2c34dfd3bfc.png">

**Comment by isunaslabs** [comment]
Got it!

**Comment by isunaslabs** [comment]
This issue is fixed
